Structure Box Item: chest
Structure Box Display Name: ยง6Structure Box
Structure Box Instruction Message:
#Determines if the structure box must be placed inside of a region of supported anti-griefing plugins
Restrict to regions:
  Enabled: false
  Exceptions:
    - Merchantman
    - MM
Free space:
  Require free space: true
  Blocks to ignore:
    - grass